{
 "title": "SHT4x Sensor Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "SHT4x Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "sht4x_temperature_celsius", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "SHT4x Temperature Averaged (°C)",
   "type": "timeseries",
   "description": "SHT4x Temperature\nAveraged using a sliding window to smooth oscillations.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(sht4x_temperature_celsius[15m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "SHT4x Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sht4x_humidity_percent", "legendFormat": "{{host}}" }
   ]
  }
 ]
}